<a href="https://colab.research.google.com/github/MariosGvr/Pytorch-notebooks-and-resources/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Book resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
# torch is pre-installed in colab
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


## Introduction to tensors



### Creating tensors

Doc: https://pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalar
scalar = torch.tensor(7)
print('scalar:', scalar)
print('scalar.ndim:', scalar.ndim)
# get tensor as python int
print('scalar.item():', scalar.item())

scalar: tensor(7)
scalar.ndim: 0
scalar.item(): 7


In [ ]:
# Vector
vector = torch.tensor([7,7])
print('vector:', vector)
print('vector.ndim:', vector.ndim)
print('vector.shape:', vector.shape)

vector: tensor([7, 7])
vector.ndim: 1
vector.shape: torch.Size([2])


In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
print('MATRIX:', MATRIX)
print('MATRIX.ndim:', MATRIX.ndim)
print('MATRIX.shape:', MATRIX.shape)

MATRIX: tensor([[ 7,  8],
        [ 9, 10]])
MATRIX.ndim: 2
MATRIX.shape: torch.Size([2, 2])


In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [7,8,9]]])
print('TENSOR:', TENSOR)
print('TENSOR.ndim:', TENSOR.ndim)
print('TENSOR.shape:', TENSOR.shape)

TENSOR = torch.tensor([
                        [[[1,2,3,5],
                        [3,6,9,5],
                        [7,8,9,5]],
                       [[1,2,3,5],
                        [3,6,9,5],
                        [7,8,9,5]],
                       [[1,2,3,5],
                        [3,6,9,5],
                        [7,8,9,5]],
                       [[1,2,3,5],
                        [3,6,9,5],
                        [7,8,9,5]]],

                       [[[1,2,3,5],
                        [3,6,9,5],
                        [7,8,9,5]],
                       [[1,2,3,5],
                        [3,6,9,5],
                        [7,8,9,5]],
                       [[1,2,3,5],
                        [3,6,9,5],
                        [7,8,9,5]],
                       [[1,2,3,5],
                        [3,6,9,5],
                        [7,8,9,5]]]
                        ])

print('TENSOR:', TENSOR)
print('TENSOR.ndim:', TENSOR.ndim)
print('TENSOR.shape:', TENSOR.shape)

TENSOR: tensor([[[1, 2, 3],
         [3, 6, 9],
         [7, 8, 9]]])
TENSOR.ndim: 3
TENSOR.shape: torch.Size([1, 3, 3])
TENSOR: tensor([[[[1, 2, 3, 5],
          [3, 6, 9, 5],
          [7, 8, 9, 5]],

         [[1, 2, 3, 5],
          [3, 6, 9, 5],
          [7, 8, 9, 5]],

         [[1, 2, 3, 5],
          [3, 6, 9, 5],
          [7, 8, 9, 5]],

         [[1, 2, 3, 5],
          [3, 6, 9, 5],
          [7, 8, 9, 5]]],


        [[[1, 2, 3, 5],
          [3, 6, 9, 5],
          [7, 8, 9, 5]],

         [[1, 2, 3, 5],
          [3, 6, 9, 5],
          [7, 8, 9, 5]],

         [[1, 2, 3, 5],
          [3, 6, 9, 5],
          [7, 8, 9, 5]],

         [[1, 2, 3, 5],
          [3, 6, 9, 5],
          [7, 8, 9, 5]]]])
TENSOR.ndim: 4
TENSOR.shape: torch.Size([2, 4, 3, 4])


### Random tensors

Random tesnors are important because many NN learn by starting with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Doc: https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create random tensor of shape/size (3,4)
random_tensor = torch.rand(3,4)
print('random_tensor:\n', random_tensor)
print('random_tensor.ndim:', random_tensor.ndim)
print('random_tensor.shape:', random_tensor.shape)

random_tensor:
 tensor([[0.9459, 0.2145, 0.5711, 0.7303],
        [0.8788, 0.5958, 0.8025, 0.2095],
        [0.9561, 0.2893, 0.7304, 0.9732]])
random_tensor.ndim: 2
random_tensor.shape: torch.Size([3, 4])


In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #colour channel, height, width 
                          #torch.rand(3,224,224)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

Doc: https://pytorch.org/docs/stable/generated/torch.arange.html

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(1,11)
print('one_to_ten:', one_to_ten)

zero_to_1000 = torch.arange(start=0, end=1000, step=42)
print('zero_to_1000:', zero_to_1000)

one_to_ten: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
zero_to_1000: tensor([  0,  42,  84, 126, 168, 210, 252, 294, 336, 378, 420, 462, 504, 546,
        588, 630, 672, 714, 756, 798, 840, 882, 924, 966])


In [ ]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you will run into with PyTorch & deep learning

1. Tensors not right datatype
1. Tensors not right shape
1. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3., 6., 9.], dtype=None)
print('float_32_tensor:', float_32_tensor)
print('float_32_tensor.dtype:', float_32_tensor.dtype) #default dtype = float32

float_32_tensor: tensor([3., 6., 9.])
float_32_tensor.dtype: torch.float32


In [ ]:
# Float 16 tensor
float_16_tensor = torch.tensor([3., 6., 9.], dtype=torch.float16)
print('float_16_tensor:', float_16_tensor)
print('float_16_tensor.dtype:', float_16_tensor.dtype)

float_16_tensor: tensor([3., 6., 9.], dtype=torch.float16)
float_16_tensor.dtype: torch.float16


In [ ]:
# Float 32 tensor - The most important parameters when creating tensors
float_32_tensor = torch.tensor([3., 6., 9.], 
                               dtype=None, # What data type is the tensors, Default=float32 (https://pytorch.org/docs/stable/tensors.html#data-types)
                               device=None, # What device is your tensor on, Default: 'cpu', change to 'cuda'
                               requires_grad=False) # When we want pytorch to track gradients
print('float_32_tensor:', float_32_tensor)
print('float_32_tensor.dtype:', float_32_tensor.dtype) #default dtype = float32

float_32_tensor: tensor([3., 6., 9.])
float_32_tensor.dtype: torch.float32


In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
# or
float_16_tensor = float_32_tensor.type(torch.half)

In [ ]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor * float_32_tensor

### Getting attributes from tensors

1. Tensors not right datatype - to get datatype from tensors can use `tensor.dtype`
1. Tensors not right shape - to get shape from tensors can use `tensor.shape`
1. Tensors not on the right device - to get device from tensors can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2733, 0.0283, 0.3842, 0.5301],
        [0.9077, 0.1722, 0.6022, 0.6761],
        [0.9014, 0.2610, 0.9806, 0.1463]])

In [ ]:
# Find out attributes about some_tensor
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of devtensorice: cpu


### Manipulating tensors - Tensors operations

Tensor operation include
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplication in NNs and DL:
1. Element-wise multiplication
1. Matrix Multiplication (dot product)


There are two rules that performing Matrix Multiplication needs to satisfy:
1. The **inner dimensions** must match:
    * `(3,2) @ (3,5)` won't work
    * `(3,2) @ (2,5)` will work

1. The resulting matrix has the shape of the **outer dimensions**:
    * `(3,2) @ (2,5)` -> `(3,5)`
    * `(9,7) @ (7,2)` -> `(9,2)`

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor, end=" = ")
print(tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
print(tensor, "@", tensor, end=" = ")
print(torch.matmul(tensor, tensor))

tensor([1, 2, 3]) @ tensor([1, 2, 3]) = tensor(14)


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 124 µs, sys: 17 µs, total: 141 µs
Wall time: 146 µs


tensor(14)

In [ ]:
%%time
tensor @ tensor

CPU times: user 126 µs, sys: 0 ns, total: 126 µs
Wall time: 131 µs


tensor(14)

### One of the most common errors in DL: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [12,13]])

# Will throw an error
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matmul)


RuntimeError: ignored

To fix our tensor shape issues we can manipulate the shape one of our tensors using **Transpose**

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8, 12],
         [10, 11, 13]]), torch.Size([2, 3]))

In [ ]:
# Now it will work
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  38],
        [ 61,  68,  88],
        [ 95, 106, 138]])

## Finding the min, max, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min(), min(x)

(tensor(1), tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max(), max(x)

(tensor(91), tensor(91), tensor(91))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum(), sum(x)

(tensor(460), tensor(460), tensor(460))

## Finding the position min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() 
#-> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0], x[x.argmin()]

(tensor(1), tensor(1))

In [ ]:
# Find the position in tensor that has the maximum value with argmax() 
#-> returns index position of target tensor where the maximum value occurs
x.argmax()

tensor(9)

In [ ]:
x[9], x[x.argmax()]

(tensor(91), tensor(91))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a *view* of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side-by-side (hstack)
    1. stack: https://pytorch.org/docs/stable/generated/torch.stack.html
    1. vstack: https://pytorch.org/docs/stable/generated/torch.vstack.html
    1. hstack: https://pytorch.org/docs/stable/generated/torch.hstack.html

* Squeeze - removes all `1` dimensions from a tensor (https://pytorch.org/docs/stable/generated/torch.squeeze.html)
* Unsqueeze - adds a `1` dimension to a target tensor (https://pytorch.org/docs/stable/generated/torch.unsqueeze.html)
* Permute - return a *view* of the imput with dimensions permuted (swapped) in a certain way (https://pytorch.org/docs/stable/generated/torch.permute.html

In [ ]:
x = torch.arange(1, 10)
x, x.shape, x.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]), torch.int64)

In [ ]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [ ]:
# Add an extra dimension - must be compatible with the tensor shape
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape, x_reshaped.dtype

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 torch.float32)

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape, x_reshaped.dtype

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]), torch.float32)

In [ ]:
# Change the view - SHARES SAME MEMORY WITH TENSOR - z is just a different view of x
z = x.view(1,9)
z, z.shape, z.dtype

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 torch.float32)

In [ ]:
# Changing z changes x
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x]) #default dim=0 | =vstack
x_stacked, x_stacked.shape, x_stacked.dtype

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]),
 torch.float32)

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1) # NOT the same with hstack
x_stacked, x_stacked.shape, x_stacked.dtype

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]), torch.Size([9, 4]), torch.float32)

In [ ]:
# hstack
torch.hstack([x,x,x,x]) 

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped = x.reshape(1,9)
print('x_reshaped:', x_reshaped)
print('x_reshaped.shape:', x_reshaped.shape)
print()
x_reshaped_squeezed = x_reshaped.squeeze()
print('x_reshaped_squeezed:', x_reshaped_squeezed)
print('x_reshaped_squeezed.shape:', x_reshaped_squeezed.shape)


x_reshaped: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
x_reshaped.shape: torch.Size([1, 9])

x_reshaped_squeezed: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
x_reshaped_squeezed.shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() -> adds a single dimension to a target tensor at a specific dim
print('x_reshaped_squeezed:', x_reshaped_squeezed)
print('x_reshaped_squeezed.shape:', x_reshaped_squeezed.shape)
print()

# Add extra dim on dim=0
x_reshaped_unsqueezed = x_reshaped_squeezed.unsqueeze(dim=0)
print('Dim=0:')
print('x_reshaped_unsqueezed:', x_reshaped_unsqueezed)
print('x_reshaped_unsqueezed.shape:', x_reshaped_unsqueezed.shape)
print()

# Add extra dim on dim=1 - will reshape the tensor
print('Dim=1:')
x_reshaped_unsqueezed = x_reshaped_squeezed.unsqueeze(dim=1)
print('x_reshaped_unsqueezed:', x_reshaped_unsqueezed)
print('x_reshaped_unsqueezed.shape:', x_reshaped_unsqueezed.shape)

x_reshaped_squeezed: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
x_reshaped_squeezed.shape: torch.Size([9])

Dim=0:
x_reshaped_unsqueezed: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
x_reshaped_unsqueezed.shape: torch.Size([1, 9])

Dim=1:
x_reshaped_unsqueezed: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
x_reshaped_unsqueezed.shape: torch.Size([9, 1])


In [ ]:
# torch.permute() -> rearranges the dimensions of a target in a specific order
# permute = rearrange (kinda)
x_original = torch.rand(size=(224,224,3))

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
# or
#x_permuted = torch.permute(x_original, (2, 0, 1))


print(f'Previous shape:{x_original.shape}')
print(f'New shape:{x_permuted.shape}')

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 42

In [ ]:
x_permuted[0,0,0]

tensor(42.)

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar with indexing with Numpy

In [ ]:
# Create tensor
x = torch.arange(1., 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]), torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor (dim=0)
x[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0,0]

(tensor([1., 2., 3.]), tensor([1., 2., 3.]))

In [ ]:
# Let's index on the most inner bracket (last dimension, dim=2)
x[0][0][0], x[0,0,0]

(tensor(1.), tensor(1.))

In [ ]:
# You can also use ':' to select "all" of a target dimension
x[:,0]

tensor([[1., 2., 3.]])

In [ ]:
# Get all values of the 0th and the 1st dimensions but only index 1 of 2nd dimension
x[:,:, 1]

tensor([[2., 5., 8.]])

In [ ]:
# Get all values of the 0th but only the 1 index of 1st of 2nd dimension
x[:,1,1] # Notice the difference with x[0,1,1]

tensor([5.])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:], x[0][0], x[0,0]

(tensor([1., 2., 3.]), tensor([1., 2., 3.]), tensor([1., 2., 3.]))

In [ ]:
# Index on x to return 9
print(f'Return 9: {x[0,2,2]}')

# Index on x to return 3, 6, 9
print(f'Return 3, 6, 9: {x[0,:,2]}')


Return 9: 9.0
Return 3, 6, 9: tensor([3., 6., 9.])


## Pytorch tensors and Numpy

*  Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [20]:
# Numpy array to tensor

array = np.arange(1., 8.)
tensor = torch.from_numpy(array) # warning when converting from numpy to pytorch 
                                 # pytorch reflects numpy's default dataatype of float64 unless specified otehrwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

* Default numpy dtype: float64
* Default tensor dtype: float32

In [21]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [22]:
# Change value of array, what will this do to tensor?
array = array +  1
array, tensor

In [24]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]), dtype('float32'))

In [25]:
# Change the tensor, what will this do to the array?
tensor = tensor +  1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility
https://pytorch.org/docs/stable/notes/randomness.html

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again -> ...`


To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed is "flavour" the randomness.

In [26]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6362, 0.7520, 0.5874, 0.2445],
        [0.4350, 0.9611, 0.6567, 0.6830],
        [0.8341, 0.8181, 0.8938, 0.8550]])
tensor([[0.9630, 0.5636, 0.6037, 0.7132],
        [0.6696, 0.4502, 0.2658, 0.1859],
        [0.1322, 0.5742, 0.1257, 0.7939]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [28]:
# Let's make some random but reproducible tensors
# Set random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) #It only works for the next command
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensor and PyTorch objects on the GPUs

### 1. Getting a GPU

1. Easiest - use Google colab for a free GPU
2. Use your own GPU
3. Use cloud computing - GCP, AWS, Azure

In [2]:
# How to see the machine specs
!nvidia-smi

Fri Nov 18 17:20:04 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P8    12W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [3]:
# Check for GPU access with PyTorch

torch.cuda.is_available()

True

For PyTorch since it'a cPblw of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. Run on GPU if available, else run on CPU

In [7]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [5]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors and models on the GPU

The reason we want our tensors/models on the GPU because using a GPU results in faster computations



In [8]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device='cpu') # default

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU


In [11]:
# If tensor is on GPU, can't transform it to Numpy
# We must first set it to CPU

tesnor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tesnor_back_on_cpu

array([1, 2, 3])