<a href="https://colab.research.google.com/github/MariosGvr/Pytorch-notebooks-and-resources/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises & Extra-curriculum

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises



## 1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* The documentation on `torch.cuda`: https://pytorch.org/docs/stable/cuda.html

## 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch
tensor_1 = torch.rand(7,7)
tensor_1, tensor_1.shape

(tensor([[0.0867, 0.2868, 0.6553, 0.7845, 0.6210, 0.7388, 0.2699],
         [0.0690, 0.9270, 0.2471, 0.8512, 0.4624, 0.2122, 0.4181],
         [0.9069, 0.7921, 0.1886, 0.0010, 0.6365, 0.9307, 0.4673],
         [0.5621, 0.5566, 0.8720, 0.0601, 0.0068, 0.5051, 0.0365],
         [0.4700, 0.9329, 0.5602, 0.6912, 0.8608, 0.6067, 0.5824],
         [0.0859, 0.5663, 0.0293, 0.5843, 0.8832, 0.8598, 0.5751],
         [0.0119, 0.8788, 0.0498, 0.6610, 0.4660, 0.8285, 0.2427]]),
 torch.Size([7, 7]))

## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [8]:
tensor_2 = torch.rand(1,7)

mm_tensor = torch.matmul(tensor_1, tensor_2.T)
mm_tensor, mm_tensor.shape

(tensor([[1.3607],
         [1.5384],
         [1.5573],
         [1.7827],
         [1.8837],
         [1.6727],
         [2.8017]]), torch.Size([7, 1]))

## 4. Set the random seed to `0` and do 2 & 3 over again.

In [21]:
torch.manual_seed(0)
tensor_1 = torch.rand(7,7)

torch.manual_seed(0)
tensor_2 = torch.rand(1,7)

mm_tensor = torch.matmul(tensor_1, tensor_2.T)
mm_tensor, mm_tensor.shape, tensor_1 == tensor_2

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]),
 tensor([[ True,  True,  True,  True,  True,  True,  True],
         [False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False]]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)

In [3]:
if torch.cuda.is_available():
    print("There is cuda available.")
    torch.cuda.manual_seed(1234)

There is cuda available.


## 6. Create two random tensors of shape `(2, 3)` on GPU


In [4]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

# Create a tensor (default on the GPU)
torch.cuda.manual_seed(1234)
tensor_GPU_1 = torch.rand(2,3, device=device)

# Create a tensor (default on the GPU)
torch.cuda.manual_seed(1234)
tensor_GPU_2 = torch.rand(2,3, device=device)


# Tensor on GPU
print(tensor_GPU_1, tensor_GPU_1.device)
print(tensor_GPU_2, tensor_GPU_2.device)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') cuda:0
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') cuda:0


## 7. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this).

In [5]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

# Create a tensor (default on the GPU)
torch.cuda.manual_seed(1234)
tensor_GPU_1 = torch.rand(2,3).to(device)

# Create a tensor (default on the GPU)
torch.cuda.manual_seed(1234)
tensor_GPU_2 = torch.rand(2,3).to(device)


# Tensor on GPU
print(tensor_GPU_1, tensor_GPU_1.device)
print(tensor_GPU_2, tensor_GPU_2.device)

tensor([[0.2736, 0.2404, 0.8937],
        [0.5046, 0.0914, 0.2614]], device='cuda:0') cuda:0
tensor([[0.6602, 0.0267, 0.4142],
        [0.4355, 0.5469, 0.3788]], device='cuda:0') cuda:0


## 8. Perform a matrix multiplication on the tensors you created in 7).

In [7]:
mm_tensor_GPU = torch.matmul(tensor_GPU_1, tensor_GPU_2.T)
mm_tensor_GPU

tensor([[0.5572, 0.5891],
        [0.4438, 0.3688]], device='cuda:0')

## 9. Find the maximum and minimum values of the output of 8.

In [11]:
mm_tensor_GPU.max(), torch.max(mm_tensor_GPU)

(tensor(0.5891, device='cuda:0'), tensor(0.5891, device='cuda:0'))

In [12]:
mm_tensor_GPU.min(), torch.min(mm_tensor_GPU)

(tensor(0.3688, device='cuda:0'), tensor(0.3688, device='cuda:0'))

## 10. Find the maximum and minimum index values of the output of 8.

In [13]:
mm_tensor_GPU.argmax(), mm_tensor_GPU.argmin()

(tensor(1, device='cuda:0'), tensor(3, device='cuda:0'))

##  10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [14]:
torch.manual_seed(7)
tensor_10 = torch.rand(1,1,1,10)
print('Original tensor:', tensor_10)
print('Original tensor shape:', tensor_10.shape)


new_tensor_10 = tensor_10.squeeze()
print('New tensor:', new_tensor_10)
print('New tensor shape:', new_tensor_10.shape)


Original tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Original tensor shape: torch.Size([1, 1, 1, 10])
New tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
New tensor shape: torch.Size([10])
